### ISSUE TITLE
gym 初始化为什么分两步

### ISSUE THREAD

**Issue by dryyun** [ZhenhangTung/GoGym#16]
````
var gym = new(GoGym.Gym)
gym.Prepare()
`````
其实完全可以通过一步搞定，写一个 New 方法，合并这两步
所以为什么分层了两步？是基于什么考虑 ？

**Comment by ZhenhangTung** [comment]
十分感谢你提出这个问题。你可以在[GymService这个Interface中，看到Prepare method](https://github.com/ZhenhangTung/GoGym/blob/master/gym_service_interface.go#L9)。我的所有service都implements了service interface，所以会有Prepare()。你的建议十分好，我可以写个方法来包装一下，对于用户更简洁。下个小版本中我加入，也欢迎你提交PR。

**Comment by ZhenhangTung** [comment]
按照你提供的思路，大致将会是
```
func (g *Gym) New() *Gym {
  gym := new(GoGym.Gym)
  gym.Prepare()
  return gym
}
```

**Comment by dryyun** [comment]
很简单的功能。你都写好了。
最近在看源码，学习一下。

**Comment by ZhenhangTung** [comment]
嗯嗯，有问题或者建议欢迎沟通，邮件微信或者PR都行。
